# Generated by Django 3.1 on 2020-08-26 11:46

import advertisement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adpost',
            name='image',
            field=models.ImageField(blank=True, default='180px-FC_Barcelona_(crest).svg.png', null=True, upload_to=advertisement.models.upload_location),
        ),
    ]
