# Generated by Django 3.1 on 2020-08-27 04:02

import advertisement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_auto_20200826_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adpost',
            name='image',
            field=models.ImageField(null=True, upload_to=advertisement.models.upload_location),
        ),
    ]
