# Generated by Django 3.1 on 2020-08-27 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0004_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
