# Generated by Django 3.1 on 2020-08-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0006_images_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.AddField(
            model_name='adpost',
            name='location',
            field=models.CharField(blank=True, choices=[('Audio', (('vinyl', 'Vinyl'), ('cd', 'CD'))), ('Video', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('unknown', 'Unknown')], max_length=100),
        ),
        migrations.AddField(
            model_name='adpost',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default='10', max_digits=6),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
