# Generated by Django 3.1 on 2020-08-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0007_auto_20200828_0529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adpost',
            name='location',
        ),
        migrations.AddField(
            model_name='adpost',
            name='body_type',
            field=models.CharField(choices=[], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='adpost',
            name='city',
            field=models.CharField(blank=True, choices=[], max_length=100),
        ),
        migrations.AddField(
            model_name='adpost',
            name='district',
            field=models.CharField(choices=[('Audio', (('vinyl', 'Vinyl'), ('cd', 'CD'))), ('Video', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('unknown', 'Unknown')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adpost',
            name='fuel_type',
            field=models.CharField(choices=[], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='adpost',
            name='is_negotiable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adpost',
            name='transmission',
            field=models.CharField(choices=[], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adpost',
            name='vehicle_brand',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='adpost',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='adpost',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
