# Generated by Django 3.1 on 2020-09-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0008_auto_20200828_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adpost',
            name='body_type',
            field=models.CharField(choices=[('vinyl', 'Vinyl')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='adpost',
            name='city',
            field=models.CharField(blank=True, choices=[('vinyl', 'Vinyl'), ('cd', 'CD')], max_length=100),
        ),
        migrations.AlterField(
            model_name='adpost',
            name='fuel_type',
            field=models.CharField(choices=[('vinyl', 'Vinyl')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='adpost',
            name='transmission',
            field=models.CharField(choices=[('vinyl', 'Vinyl')], max_length=100, null=True),
        ),
    ]
